"""Stubs for the C geohash module."""

from typing import Callable, Iterable

from pygeohash.geohash_types import ExactLatLong, LatLong

# Note: GeohashPrecision is treated as int here as the C layer expects an integer.
# The higher-level Python wrapper can use the TypeAlias if desired.

def encode(latitude: float, longitude: float, precision: int) -> str: ...
def encode_strictly(latitude: float, longitude: float, precision: int) -> str: ...
def decode(geohash: str) -> LatLong: ...
def decode_exactly(geohash: str) -> ExactLatLong: ...
def encode_many(
    latitudes: Iterable[float],
    longitudes: Iterable[float],
    precision: int,
    scalar: Callable[[float, float, int], str],
) -> list[str]: ...
def decode_many(geohashes: Iterable[str], scalar: Callable[[str], LatLong]) -> list[LatLong]: ...
def get_base32() -> str: ...
