"""Stubs for the C geohash module."""

from pygeohash.geohash_types import ExactLatLong, LatLong

# Note: GeohashPrecision is treated as int here as the C layer expects an integer.
# The higher-level Python wrapper can use the TypeAlias if desired.

def encode(latitude: float, longitude: float, precision: int) -> str: ...
def encode_strictly(latitude: float, longitude: float, precision: int) -> str: ...
def decode(geohash: str) -> LatLong: ...
def decode_exactly(geohash: str) -> ExactLatLong: ...
def get_base32() -> str: ...
